import { barDataItem } from 'react-native-gifted-charts';
import {
  incomeSpacing,
  expenseSpacing,
  barWidth,
  frontColorIncome,
  frontColorExpense,
} from './consts';

export const mockChartData: barDataItem[] = [
  {
    label: 'Jan',
    value: 4000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 2000,
    frontColor: frontColorExpense,
    barWidth,
    spacing: expenseSpacing,
  },
  {
    label: 'Feb',
    value: 3000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 1500,
    frontColor: frontColorExpense,
    barWidth,
    spacing: expenseSpacing,
  },
  {
    label: 'Mar',
    value: 5000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 4000,
    frontColor: frontColorExpense,
    barWidth,
    spacing: expenseSpacing,
  },
  {
    label: 'Apr',
    value: 6000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 5000,
    frontColor: frontColorExpense,
    spacing: expenseSpacing,
    barWidth,
  },
  {
    label: 'May',
    value: 7000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 5000,
    frontColor: frontColorExpense,
    barWidth,
    spacing: expenseSpacing,
  },
  {
    label: 'Jun',
    value: 8000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 7000,
    frontColor: frontColorExpense,
    barWidth,
    spacing: expenseSpacing,
  },
  {
    label: 'Jul',
    value: 9000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 5000,
    frontColor: frontColorExpense,
    barWidth,
    spacing: expenseSpacing,
  },
  {
    label: 'Aug',
    value: 10000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 10000,
    frontColor: frontColorExpense,
    barWidth,
    spacing: expenseSpacing,
  },
  {
    label: 'Sep',
    value: 11000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 11000,
    frontColor: frontColorExpense,
    spacing: expenseSpacing,
    barWidth,
  },
  {
    label: 'Oct',
    value: 12000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 5000,
    frontColor: frontColorExpense,
    spacing: expenseSpacing,
    barWidth,
  },
  {
    label: 'Nov',
    value: 13000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 13000,
    frontColor: frontColorExpense,
    spacing: expenseSpacing,
    barWidth,
  },
  {
    label: 'Dec',
    value: 14000,
    frontColor: frontColorIncome,
    spacing: incomeSpacing,
    barWidth,
  },
  {
    value: 6000,
    frontColor: frontColorExpense,
    spacing: expenseSpacing,
    barWidth,
  },
];
