export const MEMORY_CHECK_INTERVAL = 2000; // How often to check memory usage (ms)
export const FPS_UPDATE_INTERVAL = 1000; // How often to update FPS display (ms)
export const FPS_HISTORY_SIZE = 30; // Number of FPS measurements to keep for history
export const RECENT_FPS_SAMPLES = 3; // Number of samples to use for moving average
export const FPS_THRESHOLD_GREEN = 55; // Threshold for good performance (green)
export const FPS_THRESHOLD_YELLOW = 45; // Threshold for moderate performance issues (yellow)
export const FPS_REFERENCE = 60; // Reference FPS (for calculating dropped frames)
export const MEMORY_THRESHOLD_GREEN = 60; // Threshold for good memory usage (green)
export const MEMORY_THRESHOLD_YELLOW = 80; // Threshold for moderate memory usage (yellow)
