export enum testIDs {
  avatar = 'avatar',
  avatarPlaceholder = 'avatar-placeholder',
  avatarButton = 'avatar-button',
  screenHeader = 'screen-header',
  arrowLeftButton = 'arrow-left-button',
  inputLeftIcon = 'input-left-icon',
  inputRightIcon = 'input-right-icon',
  avatarLoader = 'avatar-loader',
  avatarPicker = 'avatar-picker',
  floatingAddButton = 'floating-add-button',
  numberPad = 'number-pad',
  numberPadDisplay = 'number-pad-display',
  numberPadButton = 'number-pad-button',
  notificationsButton = 'notifications-button',
  settingsButton = 'settings-button',
  logoutButton = 'logout-button',
  mainSideMenu = 'main-side-menu',
  loader = 'loader',
  editableAvatarTouchable = 'editable-avatar-touchable',
  modalBackdrop = 'modal-backdrop',
  monthlyChartTitle = 'monthly-chart-title',
  noMonthlySummaryChartDataAvailable = 'no-monthly-summary-chart-data-available',
  inputButton = 'input-button',
  dateTimePicker = 'date-time-picker',
}
